config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :short_stories
  resources :poems
  resources :profiles
  devise_for :users

  get '/profile', to: 'profiles#show'
  get '/profile/edit', to: 'profiles#edit'
  get '/exit', to: 'profiles#exit'
  patch '/profile', to: 'profiles#update'

  get '/profile/:profile_id/composers', to: 'profiles#composers', as: 'profile_composers'


  get '/composes', to: 'homes#index', as: 'composes'

  root to: 'profiles#show'


end

app/models/poem.rb
class Poem < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  validates :metaphor, presence: true

  belongs_to :user
  has_and_belongs_to_many :tags

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /poems
  # GET /poems.json
  def index
    if params[:profile_id].present?
      @poems = Profile.find(params[:profile_id]).user.poems.page(params[:page])
    else
      @poems = current_user.present? ? current_user.poems.page(params[:page]) : Poem.all.page(params[:page])
    end
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)
    @poem.user = current_user

    if params[:tags_id].present?
      arr = params[:tags_id].split(',')
      @poem.tags = Tag.find(arr)
    end

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update

    if params[:tags_id].present?
      arr = params[:tags_id].split(',')
      @poem.tags = Tag.find(arr)
    end

    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :content, :metaphor)
    end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/_form.html.slim
= form_for @poem, html: { class: "form form-horizontal poem" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
      = f.error_span(:title)
  .form-group
    = f.label :content, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :content, class: 'form-control', data: {content_input: ''}, rows: 5
      = f.error_span(:content)
  .form-group
    = f.label :metaphor, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :metaphor, :class => 'form-control'
      = f.error_span(:metaphor)

  .form-group
    = label_tag 'tags',nil, class: 'control-label col-lg-2'
    .col-lg-10
      = text_field_tag 'tags', @poem.tags.pluck(:name).join(', '), :class => 'form-control', disabled: :disabled, data: {tags_field: ''}

  = hidden_field_tag 'tags_id', @poem.tags.pluck(:id).join(',')


  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), poems_path, :class => 'btn'

app/views/poems/edit.html.slim
- model_class = Poem
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/poems/index.html.slim
- model_class = Poem
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
= paginate @poems
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:content)
      th= model_class.human_attribute_name(:metaphor)
      th= model_class.human_attribute_name(:user_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @poems.each do |poem|
      tr
        td= link_to poem.id, poem_path(poem)
        td= link_to poem.title, poem_path(poem)
        td= raw poem.content.gsub(/\r\n/, '<br/>')
        td= poem.metaphor
        td= poem.user.email
        td=l poem.created_at
        td
          - if current_user.present? && current_user == poem.user
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_poem_path(poem), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), poem_path(poem), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          - else
            = link_to t('.show', :default => t("helpers.links.show")), poem_path(poem), :class => 'btn btn-default btn-xs'
= paginate @poems
br


= link_to t('.new', :default => t("helpers.links.new")), new_poem_path, :class => 'btn btn-primary', style: 'zoom:2;'

app/views/poems/new.html.slim
- model_class = Poem
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/poems/show.html.slim
/  - model_class = Poem
  .page-header
    h1=t '.title', :default => model_class.model_name.human.titleize

  p
    strong= model_class.human_attribute_name(:title) + ':'
    =< @poem.title
  p
    strong= model_class.human_attribute_name(:content) + ':'
    br
    = raw @poem.content.gsub(/\r\n/, '<br/>')
  p
    strong= model_class.human_attribute_name(:metaphor) + ':'
    =< @poem.metaphor
  p
    strong= model_class.human_attribute_name(:user_id) + ':'
    =< @poem.user.email


p
  h1= @poem.title
  ' by
  i
    = link_to profile_composers_path(profile_id: @poem.user.profile.id) do
      = @poem.user.profile.name
p= l @poem.created_at
table.table.table-striped
  tbody
    tr
      td= @poem.metaphor
    tr
      td= raw @poem.content.gsub(/\r\n/, '<br/>')
    tr
      td
        - @poem.tags.each do |tag|
          =< link_to composes_path(tag_name: tag.name) do
            = tag.name


hr
= link_to t('.back', :default => t("helpers.links.back")), poems_path, :class => 'btn btn-default'
'
- if current_user.present? && current_user == @poem.user
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_poem_path(@poem), :class => 'btn btn-default'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), poem_path(@poem), :method => "delete", :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))}, :class => 'btn btn-danger'