config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :short_stories
  resources :poems
  resources :profiles
  devise_for :users

  get '/profile', to: 'profiles#show'
  get '/profile/edit', to: 'profiles#edit'
  get '/exit', to: 'profiles#exit'
  patch '/profile', to: 'profiles#update'

  get '/profile/:profile_id/composers', to: 'profiles#composers', as: 'profile_composers'


  get '/composes', to: 'homes#index', as: 'composes'

  root to: 'profiles#show'


end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :email, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def exit
    sign_out current_user
    redirect_to :back
  end

  def composers
    if params[:profile_id].present?
      profile = Profile.find(params[:profile_id])
      @poems = profile.user.poems
      @short_stories = profile.user.short_stories
    end
  end

  def update
    respond_to do |format|
      if @profile.update(user_params)
        format.html { redirect_to @profile, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def user_params
    params.require(:profile).permit(:name, :biography)
  end
end

app/views/profiles/_form.html.slim
= form_for @profile, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
      = f.error_span(:name)
  .form-group
    = f.label :biography, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :biography, :class => 'form-control'
      = f.error_span(:biography)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'

app/views/profiles/composers.html.slim
.page
  .page-header
    h1 Stories
  table.table.table-striped
    thead
      tr
        th= Poem.human_attribute_name(:id)
        th= Poem.human_attribute_name(:title)
        th= Poem.human_attribute_name(:content)
        th= Poem.human_attribute_name(:short_description)
        th= Poem.human_attribute_name(:user_id)
        th= Poem.human_attribute_name(:created_at)
    tbody
      - @short_stories.each do |short_story|
        tr
          td= link_to short_story.id, short_story_path(short_story)
          td
            = link_to short_story_path(short_story) do
              = short_story.title
          td= raw short_story.content.gsub(/\r\n/, '<br/>')
          td= short_story.short_description
          td= short_story.user.name
          td=l short_story.created_at


  hr


  .page-header
    h1 Poems
    table.table.table-striped
      thead
        tr
          th= ShortStory.human_attribute_name(:id)
          th= ShortStory.human_attribute_name(:title)
          th= ShortStory.human_attribute_name(:content)
          th= ShortStory.human_attribute_name(:metaphor)
          th= ShortStory.human_attribute_name(:user_id)
          th= ShortStory.human_attribute_name(:created_at)
      tbody
        - @poems.each do |poem|
          tr
            td= link_to poem.id, poem_path(poem)
            td
              = link_to poem_path(poem) do
                = poem.title
            td= raw poem.content.gsub(/\r\n/, '<br/>')
            td= poem.metaphor
            td= poem.user.profile.name
            td=l poem.created_at

app/views/profiles/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/profiles/index.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:encrypted_password)
      th= model_class.human_attribute_name(:reset_password_token)
      th= model_class.human_attribute_name(:reset_password_sent_at)
      th= model_class.human_attribute_name(:remember_created_at)
      th= model_class.human_attribute_name(:current_sign_in_at)
      th= model_class.human_attribute_name(:last_sign_in_at)
      th= model_class.human_attribute_name(:current_sign_in_ip)
      th= model_class.human_attribute_name(:last_sign_in_ip)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:biography)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @users.each do |user|
      tr
        td= link_to user.id, user_path(user)
        td= user.email
        td= user.encrypted_password
        td= user.reset_password_token
        td= user.reset_password_sent_at
        td= user.remember_created_at
        td= user.current_sign_in_at
        td= user.last_sign_in_at
        td= user.current_sign_in_ip
        td= user.last_sign_in_ip
        td= user.name
        td= user.biography
        td=l user.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/profiles/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/profiles/show.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @profile.user.email
p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @profile.name
p
  strong= model_class.human_attribute_name(:biography) + ':'
  br
  = @profile.biography

p
  strong
    | poems count:
  =< link_to poems_path + "?profile_id=#{@profile.id}" do
    = pluralize @profile.user.poems.count, 'poem'
p
  strong
    | stories count
  =< link_to short_stories_path + "?profile_id=#{@profile.id}" do
    = pluralize@profile.user.short_stories.count, 'story'





= link_to t('.edit', :default => t("helpers.links.edit")), '/profile/edit', :class => 'btn btn-default'