config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :short_stories
  resources :poems
  resources :profiles
  devise_for :users

  get '/profile', to: 'profiles#show'
  get '/profile/edit', to: 'profiles#edit'
  get '/exit', to: 'profiles#exit'
  patch '/profile', to: 'profiles#update'

  get '/profile/:profile_id/composers', to: 'profiles#composers', as: 'profile_composers'


  get '/composes', to: 'homes#index', as: 'composes'

  root to: 'profiles#show'


end

app/models/short_story.rb
class ShortStory < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  validates :short_description, presence: true

  belongs_to :user
  has_and_belongs_to_many :tags

end

app/controllers/short_stories_controller.rb
class ShortStoriesController < ApplicationController
  before_action :set_short_story, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /short_stories
  # GET /short_stories.json
  def index
    if params[:profile_id].present?
      @short_stories = Profile.find(params[:profile_id]).user.short_stories.page(params[:page])
    else
      @short_stories = current_user.present? ? current_user.short_stories.page(params[:page]) : ShortStory.all.page(params[:page])
    end
  end

  # GET /short_stories/1
  # GET /short_stories/1.json
  def show
  end

  # GET /short_stories/new
  def new
    @short_story = ShortStory.new
  end

  # GET /short_stories/1/edit
  def edit
  end

  # POST /short_stories
  # POST /short_stories.json
  def create
    @short_story = ShortStory.new(short_story_params)
    @short_story.user = current_user

    if params[:tags_id].present?
      arr = params[:tags_id].split(',')
      @short_story.tags = Tag.find(arr)
    end

    respond_to do |format|
      if @short_story.save
        format.html { redirect_to @short_story, notice: 'Short story was successfully created.' }
        format.json { render :show, status: :created, location: @short_story }
      else
        format.html { render :new }
        format.json { render json: @short_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /short_stories/1
  # PATCH/PUT /short_stories/1.json
  def update

    if params[:tags_id].present?
      arr = params[:tags_id].split(',')
      @short_story.tags = Tag.find(arr)
    end
    respond_to do |format|
      if @short_story.update(short_story_params)
        format.html { redirect_to @short_story, notice: 'Short story was successfully updated.' }
        format.json { render :show, status: :ok, location: @short_story }
      else
        format.html { render :edit }
        format.json { render json: @short_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_stories/1
  # DELETE /short_stories/1.json
  def destroy
    @short_story.destroy
    respond_to do |format|
      format.html { redirect_to short_stories_url, notice: 'Short story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_story
      @short_story = ShortStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_story_params
      params.require(:short_story).permit(:title, :content, :short_description)
    end
end

app/helpers/short_stories_helper.rb
module ShortStoriesHelper
end

app/views/short_stories/_form.html.slim
= form_for @short_story, html: { class: "form form-horizontal short_story" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
      = f.error_span(:title)
  .form-group
    = f.label :content, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :content, :class => 'form-control', data: {content_input: ''}, rows: 5
      = f.error_span(:content)
  .form-group
    = f.label :short_description, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :short_description, :class => 'form-control'
      = f.error_span(:short_description)

  .form-group
    = label_tag 'tags', nil, class: 'control-label col-lg-2'
    .col-lg-10
      = text_field_tag 'tags', @short_story.tags.pluck(:name).join(', '), :class => 'form-control', disabled: :disabled, data: {tags_field: ''}

  = hidden_field_tag 'tags_id', @short_story.tags.pluck(:id).join(',')
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), short_stories_path, :class => 'btn'

app/views/short_stories/edit.html.slim
- model_class = ShortStory
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/short_stories/index.html.slim
- model_class = ShortStory
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
= paginate @short_stories
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:content)
      th= model_class.human_attribute_name(:short_description)
      th= model_class.human_attribute_name(:user_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @short_stories.each do |short_story|
      tr
        td= link_to short_story.id, short_story_path(short_story)
        td= link_to short_story.title, short_story_path(short_story)
        td= raw short_story.content.gsub(/\r\n/, '<br/>')
        td= short_story.short_description
        td= short_story.user.email
        td=l short_story.created_at
        td
          - if current_user.present? && current_user == short_story.user
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_short_story_path(short_story), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), short_story_path(short_story), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          - else
            = link_to t('.show', :default => t("helpers.links.show")), short_story_path(short_story), :class => 'btn btn-default btn-xs'
= paginate @short_stories
br
= link_to t('.new', :default => t("helpers.links.new")), new_short_story_path, :class => 'btn btn-primary', style: 'zoom:2;'

app/views/short_stories/new.html.slim
- model_class = ShortStory
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/short_stories/show.html.slim
p
  h1= @short_story.title
  ' by
  i
    = link_to profile_composers_path(profile_id: @short_story.user.profile.id) do
      = @short_story.user.profile.name
p= l @short_story.created_at
table.table.table-striped
  tbody
    tr
      td= @short_story.short_description
    tr
      td= raw @short_story.content.gsub(/\r\n/, '<br/>')
    tr
      td
        - @short_story.tags.each do |tag|
          =< link_to composes_path(tag_name: tag.name) do
            = tag.name


hr
= link_to t('.back', :default => t("helpers.links.back")), short_stories_path, :class => 'btn btn-default'
'
- if current_user.present? && current_user == @short_story.user
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_short_story_path(@short_story), :class => 'btn btn-default'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), short_story_path(@short_story), :method => "delete", :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))}, :class => 'btn btn-danger'