config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :short_stories
  resources :poems
  resources :profiles
  devise_for :users

  get '/profile', to: 'profiles#show'
  get '/profile/edit', to: 'profiles#edit'
  get '/exit', to: 'profiles#exit'
  patch '/profile', to: 'profiles#update'

  get '/profile/:profile_id/composers', to: 'profiles#composers', as: 'profile_composers'


  get '/composes', to: 'homes#index', as: 'composes'

  root to: 'profiles#show'


end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :poems
  has_and_belongs_to_many :short_stories

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.fetch(:tag, {})
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= form_for @tag, html: { class: "form form-horizontal tag" } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
      = f.error_span(:name)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), tags_path, :class => 'btn'

app/views/tags/edit.html.slim
- model_class = Tag
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tags/index.html.slim
- model_class = Tag
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @tags.each do |tag|
      tr
        td= link_to tag.id, tag_path(tag)
        td= tag.name
        td=l tag.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_tag_path(tag), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), tag_path(tag), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_tag_path, :class => 'btn btn-primary'

app/views/tags/new.html.slim
- model_class = Tag
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tags/show.html.slim
- model_class = Tag
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @tag.name

= link_to t('.back', :default => t("helpers.links.back")), tags_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_tag_path(@tag), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), tag_path(@tag), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'